databases:
  - name: contract-db
    plan: free
    ipAllowList: []

services:
  - name: ai-contract-bot
    type: web
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start:render
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: DATABASE_URL
        fromDatabase:
          name: contract-db
          property: connectionString
      # Optional: cache Playwright browsers between builds
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/.cache/ms-playwright
